General Fixes

diff --git a/.github/workflows/sentinel.yml b/.github/workflows/sentinel.yml
--- a/.github/workflows/sentinel.yml
+++ b/.github/workflows/sentinel.yml
@@ -16,66 +16,69 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup TF
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-      - name: Terraform Format
-        working-directory: ./tf/sentinel-policy-creation
-        id: fmt
-        run: terraform fmt -check
-      - name: Terraform Init
-        working-directory: ./tf/sentinel-policy-creation
-        id: init
-        run: terraform init
-      - name: Terraform Validate
-        working-directory: ./tf/sentinel-policy-creation
-        id: validate
-        run: terraform validate -no-color
-      - name: Terraform Plan
-        working-directory: ./tf/sentinel-policy-creation
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
-        continue-on-error: true
-      - name: Update Pull Request
-        uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+        run: |
+          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+          sudo apt-get update && sudo apt-get install terraform
+      #   with:
+      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+      # - name: Terraform Format
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   id: fmt
+      #   run: terraform fmt -check
+      # - name: Terraform Init
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   id: init
+      #   run: terraform init
+      # - name: Terraform Validate
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   id: validate
+      #   run: terraform validate -no-color
+      # - name: Terraform Plan
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color
+      #   continue-on-error: true
+      # - name: Update Pull Request
+      #   uses: actions/github-script@0.9.0
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
 
-            <details><summary>Show Plan</summary>
+      #       <details><summary>Show Plan</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
 
-            </details>
+      #       </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-      - name: Terraform Plan Status
-        working-directory: ./tf/sentinel-policy-creation
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Apply
-        env:
-          TF_VAR_vcs_oauth_key: ${{ secrets.VCS_OAUTH_KEY }}
-        working-directory: ./tf/sentinel-policy-creation
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
+      #       github.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+      # - name: Terraform Plan Status
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+      # - name: Terraform Apply
+      #   env:
+      #     TF_VAR_vcs_oauth_key: ${{ secrets.VCS_OAUTH_KEY }}
+      #   working-directory: ./tf/sentinel-policy-creation
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve
 
 
 
